// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: shared/proto/ats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resume         *ResumeData            `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	JobDescription string                 `protobuf:"bytes,2,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_shared_proto_ats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_ats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_ats_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationRequest) GetResume() *ResumeData {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *ValidationRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

type ATSScore struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Score           int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"` // 0-100
	Feedback        []string               `protobuf:"bytes,2,rep,name=feedback,proto3" json:"feedback,omitempty"`
	MissingKeywords []string               `protobuf:"bytes,3,rep,name=missing_keywords,json=missingKeywords,proto3" json:"missing_keywords,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ATSScore) Reset() {
	*x = ATSScore{}
	mi := &file_shared_proto_ats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATSScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATSScore) ProtoMessage() {}

func (x *ATSScore) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_ats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATSScore.ProtoReflect.Descriptor instead.
func (*ATSScore) Descriptor() ([]byte, []int) {
	return file_shared_proto_ats_proto_rawDescGZIP(), []int{1}
}

func (x *ATSScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ATSScore) GetFeedback() []string {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ATSScore) GetMissingKeywords() []string {
	if x != nil {
		return x.MissingKeywords
	}
	return nil
}

var File_shared_proto_ats_proto protoreflect.FileDescriptor

const file_shared_proto_ats_proto_rawDesc = "" +
	"\n" +
	"\x16shared/proto/ats.proto\x12\x03ats\x1a\x19shared/proto/resume.proto\"h\n" +
	"\x11ValidationRequest\x12*\n" +
	"\x06resume\x18\x01 \x01(\v2\x12.resume.ResumeDataR\x06resume\x12'\n" +
	"\x0fjob_description\x18\x02 \x01(\tR\x0ejobDescription\"g\n" +
	"\bATSScore\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x02 \x03(\tR\bfeedback\x12)\n" +
	"\x10missing_keywords\x18\x03 \x03(\tR\x0fmissingKeywords2E\n" +
	"\n" +
	"ATSService\x127\n" +
	"\x0eValidateResume\x12\x16.ats.ValidationRequest\x1a\r.ats.ATSScoreB&Z$github.com/iprotoresume/shared/protob\x06proto3"

var (
	file_shared_proto_ats_proto_rawDescOnce sync.Once
	file_shared_proto_ats_proto_rawDescData []byte
)

func file_shared_proto_ats_proto_rawDescGZIP() []byte {
	file_shared_proto_ats_proto_rawDescOnce.Do(func() {
		file_shared_proto_ats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_ats_proto_rawDesc), len(file_shared_proto_ats_proto_rawDesc)))
	})
	return file_shared_proto_ats_proto_rawDescData
}

var file_shared_proto_ats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_ats_proto_goTypes = []any{
	(*ValidationRequest)(nil), // 0: ats.ValidationRequest
	(*ATSScore)(nil),          // 1: ats.ATSScore
	(*ResumeData)(nil),        // 2: resume.ResumeData
}
var file_shared_proto_ats_proto_depIdxs = []int32{
	2, // 0: ats.ValidationRequest.resume:type_name -> resume.ResumeData
	0, // 1: ats.ATSService.ValidateResume:input_type -> ats.ValidationRequest
	1, // 2: ats.ATSService.ValidateResume:output_type -> ats.ATSScore
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_ats_proto_init() }
func file_shared_proto_ats_proto_init() {
	if File_shared_proto_ats_proto != nil {
		return
	}
	file_shared_proto_resume_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_ats_proto_rawDesc), len(file_shared_proto_ats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_ats_proto_goTypes,
		DependencyIndexes: file_shared_proto_ats_proto_depIdxs,
		MessageInfos:      file_shared_proto_ats_proto_msgTypes,
	}.Build()
	File_shared_proto_ats_proto = out.File
	file_shared_proto_ats_proto_goTypes = nil
	file_shared_proto_ats_proto_depIdxs = nil
}
