// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: shared/proto/ats.proto

package ats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ATSService_ValidateResume_FullMethodName = "/ats.ATSService/ValidateResume"
)

// ATSServiceClient is the client API for ATSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ATSServiceClient interface {
	ValidateResume(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ATSScore, error)
}

type aTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewATSServiceClient(cc grpc.ClientConnInterface) ATSServiceClient {
	return &aTSServiceClient{cc}
}

func (c *aTSServiceClient) ValidateResume(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ATSScore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ATSScore)
	err := c.cc.Invoke(ctx, ATSService_ValidateResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ATSServiceServer is the server API for ATSService service.
// All implementations must embed UnimplementedATSServiceServer
// for forward compatibility.
type ATSServiceServer interface {
	ValidateResume(context.Context, *ValidationRequest) (*ATSScore, error)
	mustEmbedUnimplementedATSServiceServer()
}

// UnimplementedATSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedATSServiceServer struct{}

func (UnimplementedATSServiceServer) ValidateResume(context.Context, *ValidationRequest) (*ATSScore, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateResume not implemented")
}
func (UnimplementedATSServiceServer) mustEmbedUnimplementedATSServiceServer() {}
func (UnimplementedATSServiceServer) testEmbeddedByValue()                    {}

// UnsafeATSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ATSServiceServer will
// result in compilation errors.
type UnsafeATSServiceServer interface {
	mustEmbedUnimplementedATSServiceServer()
}

func RegisterATSServiceServer(s grpc.ServiceRegistrar, srv ATSServiceServer) {
	// If the following call panics, it indicates UnimplementedATSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ATSService_ServiceDesc, srv)
}

func _ATSService_ValidateResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATSServiceServer).ValidateResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATSService_ValidateResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATSServiceServer).ValidateResume(ctx, req.(*ValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ATSService_ServiceDesc is the grpc.ServiceDesc for ATSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ATSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ats.ATSService",
	HandlerType: (*ATSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateResume",
			Handler:    _ATSService_ValidateResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/ats.proto",
}
