// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: shared/proto/resume.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResumeData represents the structured data of a user's resume.
type ResumeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills        []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Experience    []*Experience          `protobuf:"bytes,6,rep,name=experience,proto3" json:"experience,omitempty"`
	Education     []*Education           `protobuf:"bytes,7,rep,name=education,proto3" json:"education,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeData) Reset() {
	*x = ResumeData{}
	mi := &file_shared_proto_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeData) ProtoMessage() {}

func (x *ResumeData) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeData.ProtoReflect.Descriptor instead.
func (*ResumeData) Descriptor() ([]byte, []int) {
	return file_shared_proto_resume_proto_rawDescGZIP(), []int{0}
}

func (x *ResumeData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ResumeData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResumeData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResumeData) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResumeData) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeData) GetExperience() []*Experience {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *ResumeData) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

type Experience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_shared_proto_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_shared_proto_resume_proto_rawDescGZIP(), []int{1}
}

func (x *Experience) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Experience) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Education struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Degree         string                 `protobuf:"bytes,1,opt,name=degree,proto3" json:"degree,omitempty"`
	Institution    string                 `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	GraduationDate string                 `protobuf:"bytes,3,opt,name=graduation_date,json=graduationDate,proto3" json:"graduation_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_shared_proto_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_shared_proto_resume_proto_rawDescGZIP(), []int{2}
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *Education) GetGraduationDate() string {
	if x != nil {
		return x.GraduationDate
	}
	return ""
}

// TailorRequest is used to request a tailored resume based on a job description.
type TailorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalResume *ResumeData            `protobuf:"bytes,1,opt,name=original_resume,json=originalResume,proto3" json:"original_resume,omitempty"`
	JobDescription string                 `protobuf:"bytes,2,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailorRequest) Reset() {
	*x = TailorRequest{}
	mi := &file_shared_proto_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorRequest) ProtoMessage() {}

func (x *TailorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorRequest.ProtoReflect.Descriptor instead.
func (*TailorRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_resume_proto_rawDescGZIP(), []int{3}
}

func (x *TailorRequest) GetOriginalResume() *ResumeData {
	if x != nil {
		return x.OriginalResume
	}
	return nil
}

func (x *TailorRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

type TailorResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TailoredResume *ResumeData            `protobuf:"bytes,1,opt,name=tailored_resume,json=tailoredResume,proto3" json:"tailored_resume,omitempty"`
	CoverLetter    string                 `protobuf:"bytes,2,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TailorResponse) Reset() {
	*x = TailorResponse{}
	mi := &file_shared_proto_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailorResponse) ProtoMessage() {}

func (x *TailorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailorResponse.ProtoReflect.Descriptor instead.
func (*TailorResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_resume_proto_rawDescGZIP(), []int{4}
}

func (x *TailorResponse) GetTailoredResume() *ResumeData {
	if x != nil {
		return x.TailoredResume
	}
	return nil
}

func (x *TailorResponse) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

var File_shared_proto_resume_proto protoreflect.FileDescriptor

const file_shared_proto_resume_proto_rawDesc = "" +
	"\n" +
	"\x19shared/proto/resume.proto\x12\x06resume\"\xec\x01\n" +
	"\n" +
	"ResumeData\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x122\n" +
	"\n" +
	"experience\x18\x06 \x03(\v2\x12.resume.ExperienceR\n" +
	"experience\x12/\n" +
	"\teducation\x18\a \x03(\v2\x11.resume.EducationR\teducation\"\x98\x01\n" +
	"\n" +
	"Experience\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"n\n" +
	"\tEducation\x12\x16\n" +
	"\x06degree\x18\x01 \x01(\tR\x06degree\x12 \n" +
	"\vinstitution\x18\x02 \x01(\tR\vinstitution\x12'\n" +
	"\x0fgraduation_date\x18\x03 \x01(\tR\x0egraduationDate\"u\n" +
	"\rTailorRequest\x12;\n" +
	"\x0foriginal_resume\x18\x01 \x01(\v2\x12.resume.ResumeDataR\x0eoriginalResume\x12'\n" +
	"\x0fjob_description\x18\x02 \x01(\tR\x0ejobDescription\"p\n" +
	"\x0eTailorResponse\x12;\n" +
	"\x0ftailored_resume\x18\x01 \x01(\v2\x12.resume.ResumeDataR\x0etailoredResume\x12!\n" +
	"\fcover_letter\x18\x02 \x01(\tR\vcoverLetter2N\n" +
	"\rResumeService\x12=\n" +
	"\fTailorResume\x12\x15.resume.TailorRequest\x1a\x16.resume.TailorResponseB&Z$github.com/iprotoresume/shared/protob\x06proto3"

var (
	file_shared_proto_resume_proto_rawDescOnce sync.Once
	file_shared_proto_resume_proto_rawDescData []byte
)

func file_shared_proto_resume_proto_rawDescGZIP() []byte {
	file_shared_proto_resume_proto_rawDescOnce.Do(func() {
		file_shared_proto_resume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_resume_proto_rawDesc), len(file_shared_proto_resume_proto_rawDesc)))
	})
	return file_shared_proto_resume_proto_rawDescData
}

var file_shared_proto_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_proto_resume_proto_goTypes = []any{
	(*ResumeData)(nil),     // 0: resume.ResumeData
	(*Experience)(nil),     // 1: resume.Experience
	(*Education)(nil),      // 2: resume.Education
	(*TailorRequest)(nil),  // 3: resume.TailorRequest
	(*TailorResponse)(nil), // 4: resume.TailorResponse
}
var file_shared_proto_resume_proto_depIdxs = []int32{
	1, // 0: resume.ResumeData.experience:type_name -> resume.Experience
	2, // 1: resume.ResumeData.education:type_name -> resume.Education
	0, // 2: resume.TailorRequest.original_resume:type_name -> resume.ResumeData
	0, // 3: resume.TailorResponse.tailored_resume:type_name -> resume.ResumeData
	3, // 4: resume.ResumeService.TailorResume:input_type -> resume.TailorRequest
	4, // 5: resume.ResumeService.TailorResume:output_type -> resume.TailorResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_resume_proto_init() }
func file_shared_proto_resume_proto_init() {
	if File_shared_proto_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_resume_proto_rawDesc), len(file_shared_proto_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_resume_proto_goTypes,
		DependencyIndexes: file_shared_proto_resume_proto_depIdxs,
		MessageInfos:      file_shared_proto_resume_proto_msgTypes,
	}.Build()
	File_shared_proto_resume_proto = out.File
	file_shared_proto_resume_proto_goTypes = nil
	file_shared_proto_resume_proto_depIdxs = nil
}
