# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto import resume_pb2 as shared_dot_proto_dot_resume__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shared/proto/resume_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TailorResume = channel.unary_unary(
                '/resume.AIService/TailorResume',
                request_serializer=shared_dot_proto_dot_resume__pb2.TailorRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_resume__pb2.TailorResponse.FromString,
                _registered_method=True)
        self.AnalyzeResume = channel.unary_unary(
                '/resume.AIService/AnalyzeResume',
                request_serializer=shared_dot_proto_dot_resume__pb2.AnalyzeResumeRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_resume__pb2.AnalyzeResumeResponse.FromString,
                _registered_method=True)
        self.GenerateInterviewQuestions = channel.unary_unary(
                '/resume.AIService/GenerateInterviewQuestions',
                request_serializer=shared_dot_proto_dot_resume__pb2.InterviewPrepRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_resume__pb2.InterviewPrepResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TailorResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateInterviewQuestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TailorResume': grpc.unary_unary_rpc_method_handler(
                    servicer.TailorResume,
                    request_deserializer=shared_dot_proto_dot_resume__pb2.TailorRequest.FromString,
                    response_serializer=shared_dot_proto_dot_resume__pb2.TailorResponse.SerializeToString,
            ),
            'AnalyzeResume': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeResume,
                    request_deserializer=shared_dot_proto_dot_resume__pb2.AnalyzeResumeRequest.FromString,
                    response_serializer=shared_dot_proto_dot_resume__pb2.AnalyzeResumeResponse.SerializeToString,
            ),
            'GenerateInterviewQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInterviewQuestions,
                    request_deserializer=shared_dot_proto_dot_resume__pb2.InterviewPrepRequest.FromString,
                    response_serializer=shared_dot_proto_dot_resume__pb2.InterviewPrepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resume.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resume.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TailorResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resume.AIService/TailorResume',
            shared_dot_proto_dot_resume__pb2.TailorRequest.SerializeToString,
            shared_dot_proto_dot_resume__pb2.TailorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resume.AIService/AnalyzeResume',
            shared_dot_proto_dot_resume__pb2.AnalyzeResumeRequest.SerializeToString,
            shared_dot_proto_dot_resume__pb2.AnalyzeResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateInterviewQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resume.AIService/GenerateInterviewQuestions',
            shared_dot_proto_dot_resume__pb2.InterviewPrepRequest.SerializeToString,
            shared_dot_proto_dot_resume__pb2.InterviewPrepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResumePersistenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveResume = channel.unary_unary(
                '/resume.ResumePersistenceService/SaveResume',
                request_serializer=shared_dot_proto_dot_resume__pb2.SaveResumeRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_resume__pb2.SavedResume.FromString,
                _registered_method=True)
        self.ListResumes = channel.unary_unary(
                '/resume.ResumePersistenceService/ListResumes',
                request_serializer=shared_dot_proto_dot_resume__pb2.ListResumesRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_resume__pb2.ListResumesResponse.FromString,
                _registered_method=True)
        self.DeleteResume = channel.unary_unary(
                '/resume.ResumePersistenceService/DeleteResume',
                request_serializer=shared_dot_proto_dot_resume__pb2.DeleteResumeRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_resume__pb2.DeleteResumeResponse.FromString,
                _registered_method=True)


class ResumePersistenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResumePersistenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveResume': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveResume,
                    request_deserializer=shared_dot_proto_dot_resume__pb2.SaveResumeRequest.FromString,
                    response_serializer=shared_dot_proto_dot_resume__pb2.SavedResume.SerializeToString,
            ),
            'ListResumes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResumes,
                    request_deserializer=shared_dot_proto_dot_resume__pb2.ListResumesRequest.FromString,
                    response_serializer=shared_dot_proto_dot_resume__pb2.ListResumesResponse.SerializeToString,
            ),
            'DeleteResume': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResume,
                    request_deserializer=shared_dot_proto_dot_resume__pb2.DeleteResumeRequest.FromString,
                    response_serializer=shared_dot_proto_dot_resume__pb2.DeleteResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resume.ResumePersistenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resume.ResumePersistenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResumePersistenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resume.ResumePersistenceService/SaveResume',
            shared_dot_proto_dot_resume__pb2.SaveResumeRequest.SerializeToString,
            shared_dot_proto_dot_resume__pb2.SavedResume.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResumes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resume.ResumePersistenceService/ListResumes',
            shared_dot_proto_dot_resume__pb2.ListResumesRequest.SerializeToString,
            shared_dot_proto_dot_resume__pb2.ListResumesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resume.ResumePersistenceService/DeleteResume',
            shared_dot_proto_dot_resume__pb2.DeleteResumeRequest.SerializeToString,
            shared_dot_proto_dot_resume__pb2.DeleteResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
