package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/iprotoresume/gateway-go/graph/model"
	"github.com/iprotoresume/shared/proto/ats"
	"github.com/iprotoresume/shared/proto/resume"
)

// TailorResume is the resolver for the tailorResume field.
func (r *mutationResolver) TailorResume(ctx context.Context, input model.TailorResumeInput) (*model.TailorResponse, error) {
	req := &resume.TailorRequest{
		OriginalResume: &resume.ResumeData{
			FullName: input.OriginalResume.FullName,
			Email:    input.OriginalResume.Email,
			Skills:   input.OriginalResume.Skills,
			// Map other fields as needed...
		},
		JobDescription: input.JobDescription,
	}

	resp, err := r.ResumeClient.Client.TailorResume(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to tailor resume: %w", err)
	}

	return &model.TailorResponse{
		TailoredResume: &model.ResumeData{
			FullName: resp.TailoredResume.FullName,
			Email:    resp.TailoredResume.Email,
			Skills:   resp.TailoredResume.Skills,
		},
		CoverLetter: &resp.CoverLetter,
	}, nil
}

// ValidateResume is the resolver for the validateResume field.
func (r *mutationResolver) ValidateResume(ctx context.Context, input model.ValidateResumeInput) (*model.ATSScore, error) {
	req := &ats.ValidationRequest{
		Resume: &resume.ResumeData{
			FullName: input.Resume.FullName,
			Email:    input.Resume.Email,
			Skills:   input.Resume.Skills,
		},
		JobDescription: input.JobDescription,
	}

	resp, err := r.ATSClient.Client.ValidateResume(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to validate resume: %w", err)
	}

	// Helper to convert Int32 to Int
	score := int(resp.Score)

	return &model.ATSScore{
		Score:           score,
		Feedback:        resp.Feedback,
		MissingKeywords: resp.MissingKeywords,
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
