// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ATSScore struct {
	Score           int32    `json:"score"`
	Feedback        []string `json:"feedback"`
	MissingKeywords []string `json:"missingKeywords"`
}

type Education struct {
	Degree         string  `json:"degree"`
	Institution    string  `json:"institution"`
	GraduationDate *string `json:"graduationDate,omitempty"`
}

type EducationInput struct {
	Degree         string  `json:"degree"`
	Institution    string  `json:"institution"`
	GraduationDate *string `json:"graduationDate,omitempty"`
}

type Experience struct {
	Title       string  `json:"title"`
	Company     string  `json:"company"`
	StartDate   *string `json:"startDate,omitempty"`
	EndDate     *string `json:"endDate,omitempty"`
	Description *string `json:"description,omitempty"`
}

type ExperienceInput struct {
	Title       string  `json:"title"`
	Company     string  `json:"company"`
	StartDate   *string `json:"startDate,omitempty"`
	EndDate     *string `json:"endDate,omitempty"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type ResumeData struct {
	FullName   string        `json:"fullName"`
	Email      string        `json:"email"`
	Phone      *string       `json:"phone,omitempty"`
	Summary    *string       `json:"summary,omitempty"`
	Skills     []string      `json:"skills"`
	Experience []*Experience `json:"experience"`
	Education  []*Education  `json:"education"`
}

type ResumeInput struct {
	FullName   string             `json:"fullName"`
	Email      string             `json:"email"`
	Phone      *string            `json:"phone,omitempty"`
	Summary    *string            `json:"summary,omitempty"`
	Skills     []string           `json:"skills"`
	Experience []*ExperienceInput `json:"experience"`
	Education  []*EducationInput  `json:"education"`
}

type TailorResponse struct {
	TailoredResume *ResumeData `json:"tailoredResume"`
	CoverLetter    *string     `json:"coverLetter,omitempty"`
}

type TailorResumeInput struct {
	OriginalResume *ResumeInput `json:"originalResume"`
	JobDescription string       `json:"jobDescription"`
}

type ValidateResumeInput struct {
	Resume         *ResumeInput `json:"resume"`
	JobDescription string       `json:"jobDescription"`
}
